spring:
  profiles:
    default: prod
  application:
    name: auth-service
  h2:
    console:
      enabled: true
  config:
    #import: "configserver:http://localhost:8888"
    import: configserver:${CONFIG_SERVER_HOST}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: levidiaz222@gmail.com
    password: amxc hlnt ldtb wlgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 3030
  servlet:
    context-path: /auth-service

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL}
