spring:
  application:
    name: gateway
  profiles:
    default: oauth2  #eureka-off, eureka-on, oauth2
server:
  port: 4040


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    fetch-registry: true #luego true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL}
