spring:
  application:
    name: notificacion-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: levidiaz222@gmail.com
    password: amxc hlnt ldtb wlgp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 5555

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
