spring:
  application:
    name: notificacion-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: levidiaz222@gmail.com
    password: amxc hlnt ldtb wlgp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 5555

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL}
