spring:
  application:
    name: notificacion-service
    server:
      port: 8080

twilio:
  account:
    sid: ${TWILIO_SID}
  auth:
    token: ${TWILIO_TOKEN}
  whatsapp:
    from: +14155238886
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL}