spring:
  application:
    name: report-grafico
  config:
    #import: "configserver:http://localhost:8888"
    import: configserver:${CONFIG_SERVER_HOST}

server:
  port: 0
  servlet:
    context-path: /report-grafico

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
     #defaultZone: http://localhost:8761/eureka/
     defaultZone: ${EUREKA_URL}
